language: swift
os: osx
osx_image: xcode8.3
before_install:
script:
  - xcodebuild clean -scheme Extension | xcpretty
  - xcodebuild -project Extension.xcodeproj -scheme Extension -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' | xcpretty
  
