language: swift
os: osx
osx_image: xcode8.3
before_install:
  - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  - brew update
  - brew install carthage
  - carthage update
script:
  - xcodebuild clean -scheme Extension | xcpretty
  - xcodebuild -project Extension.xcodeproj -scheme Extension -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' | xcpretty
  
