language: swift
osx_image: xcode9.0
before_install:
script:
  - xcodebuild clean -scheme Extension | xcpretty
  - xcodebuild -project Extension.xcodeproj -scheme Extension -destination 'name=iPhone 7,OS=10.3' | xcpretty

  - xcodebuild clean -scheme Extension_macOS | xcpretty
  - xcodebuild -project Extension.xcodeproj -scheme Extension_macOS -destination 'arch=x86_64' | xcpretty

  - xcodebuild clean -scheme Extension_tvOS | xcpretty
  - xcodebuild -project Extension.xcodeproj -scheme Extension_tvOS -destination 'name=Apple TV 1080p,OS=9.0' | xcpretty

  - xcodebuild clean -scheme Extension_watchOS | xcpretty
  - xcodebuild -project Extension.xcodeproj -scheme Extension_watchOS -destination 'name=Apple Watch - 42mm,OS=2.0' | xcpretty
