language: swift
osx_image: xcode9.0
before_install:
script:
  - xcodebuild clean -scheme Extension | xcpretty
  - xcodebuild clean -scheme Extension_macOS | xcpretty
  - xcodebuild clean -scheme Extension_tvOS | xcpretty
  - xcodebuild clean -scheme Extension_watchOS | xcpretty

  - xcodebuild -project Extension.xcodeproj -scheme Extension -destination 'name=Generic iOS Device' | xcpretty
  - xcodebuild -project Extension.xcodeproj -scheme Extension_macOS -destination 'arch=x86_64' | xcpretty
  - xcodebuild -project Extension.xcodeproj -scheme Extension_tvOS -destination 'name=Generic tvOS Device' | xcpretty
  - xcodebuild -project Extension.xcodeproj -scheme Extension_watchOS -destination 'name=Generic watchOS Device' | xcpretty